#!/usr/bin/env python2.7
import platform
import subprocess
import sys

from pkg_resources import parse_version

"""installer for terminux."""

linux_brew_install_needed = False

def get_user_input(display_msg, expected_user_resps):
  """
  Get user input.
  """
  retry = 0
  max_user_input_retries = 3
  while retry < max_user_input_retries:
    user_resp = raw_input(display_msg)
    if user_resp in expected_user_resps:
      return user_resp  
    retry += 1

def run_cmd(cmd, error_msg):    
  ret = subprocess.call(cmd, shell=True)  
  if ret != 0:
    sys.exit(error_msg)  

def install_linux_brew():
  """install linux brew package manager"""
  print "Installing linux brew"
  brew_install_cmd = 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"'
  run_cmd(brew_install_cmd, "curl failed")

  path_update_cmd = "echo 'export PATH=\"/home/linuxbrew/.linuxbrew/bin:$PATH\"' >>~/.profile"
  run_cmd(path_update_cmd, "path update failed")

  path_update_cmd = "echo 'export MANPATH=\"/home/linuxbrew/.linuxbrew/share/man:$MANPATH\"' >>~/.profile"
  run_cmd(path_update_cmd, "manpath update failed")

  path_update_cmd = "echo 'export INFOPATH=\"/home/linuxbrew/.linuxbrew/share/info:$INFOPATH\"' >>~/.profile"
  run_cmd(path_update_cmd, "infopath update")

def install_vim():
  """
  Install latest version of vim using linux brew.
  """
  print "Installing vim using linux brew"
  cmd = "brew install vim"
  run_cmd(cmd, "vim installation failed")
  print "\nvim installation completed successfully"  

def main():
  """main function."""
  if platform.dist()[0] != "centos":
    sys.exit('Terminux is supported only on CentOs machines');  

  # Check if CentOS version is 6.10 or newer.
  centos_version = platform.dist()[1]
  terminux_min_supported_version = '6.10'

  if (parse_version(centos_version) <
       parse_version(terminux_min_supported_version)):
    display_msg = ("Terminux requires CentOs 6.10 or newer. Do you want to "
                   "update? (Y/N)") 
    expected_user_resps = ['Y', 'y', 'n', 'N']
    usr_resp = get_user_input(display_msg, expected_user_resps)
    if usr_resp is None:
      return	    

    if usr_resp == "Y" or usr_resp == "y":
      cmd = "sudo yum -y update"  
      run_cmd(cmd, "CentOs update failed. Exiting terminux")
    else:	
      sys.exit(1)

  print "\nFound CentOs version 6.10 or newer, continue.."

  # Install vim.
  install_vim()

  """Install LinuxBrew and update the ~/.profile variable."""
  if (linux_brew_install_needed):
    install_linux_brew()

if __name__ == "__main__":
  main()
